src/Entity/Activite.php
<?php

namespace App\Entity;

use App\Entity\Referentiel\Statut;
use App\Repository\ActiviteRepository;
use App\Trait\DateManagementTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActiviteRepository::class)]
class Activite
{
    use  DateManagementTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    #[ORM\Column(type: 'integer', nullable: false)]
    #[ORM\SequenceGenerator(sequenceName: 'activite_id_seq', allocationSize: 1, initialValue: 1)]
    private ?int $id = null;
    
    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, Utilisateur>
     */
    #[ORM\ManyToMany(targetEntity: Utilisateur::class)]
    private Collection $ressources;



    #[ORM\ManyToOne(inversedBy: 'activites')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Statut $statut = null;

    #[ORM\ManyToOne(inversedBy: 'activites')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Projet $projet_source = null;

    /**
     * @var Collection<int, Tache>
     */
    #[ORM\OneToMany(targetEntity: Tache::class, mappedBy: 'activite')]
    private Collection $taches;

    public function __construct()
    {
        $this->taches = new ArrayCollection();
        $this->ressources = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    //... (other properties and methods)

    public function getTitre():?string{
        return $this->titre;
    }

    public function getDescription():?string{
        return $this->description;
    }

     public function getRessources(): Collection{
        return $this->ressources;
    }
     public function setTitre(string $titre): self{
        $this->titre = $titre;
        return $this;
    }
     public function setDescription(?string $description): self{
        $this->description = $description;
        return $this;
    }
     public function setStatut(?Statut $statut): self{
        $this->statut = $statut;
        return $this;
    }
     public function addRessource(Utilisateur $utilisateur): self{
        if (!$this->ressources->contains($utilisateur)) {
            $this->ressources[] = $utilisateur;
        }
        return $this;
     }
     public function removeRessource(Utilisateur $utilisateur): self{
        $this->ressources->removeElement($utilisateur);
        return $this;
    }    
    public function getStatut():?Statut{
        return $this->statut;
    }

    public function getProjetSource(): ?Projet
    {
        return $this->projet_source;
    }

    public function setProjetSource(?Projet $projet_source): static
    {
        $this->projet_source = $projet_source;

        return $this;
    }

    /**
     * @return Collection<int, Tache>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): static
    {
        if (!$this->taches->contains($tach)) {
            $this->taches->add($tach);
            $tach->setActivite($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): static
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getActivite() === $this) {
                $tach->setActivite(null);
            }
        }

        return $this;
    }

}

src/Form/ActiviteType.php
<?php

namespace App\Form;

use App\Entity\Activite;
use App\Entity\Projet;
use App\Entity\Referentiel\Statut;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActiviteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_debut_estimee', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('date_fin_estimee', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('date_debut_reel', DateTimeType::class, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('date_fin_reel', DateTimeType::class, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => ['class' => 'form-control'],
            ])
            ->add('ressources', EntityType::class, [
                'class' => Utilisateur::class,
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true, // Set to true if you want checkboxes instead of a select list
        
            ])
            ->add('statut', EntityType::class, [
                'class' => Statut::class,
                'choice_label' => 'nom', 
        
            ])
            ->add('projet_source', EntityType::class, [
                'class' => Projet::class,
                'choice_label' => 'titre',  
                'attr' => ['class' => 'form-select'],
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Activite::class,
        ]);
    }
}

src/Controller/ActiviteController.php
<?php

namespace App\Controller;

use App\Entity\Activite;
use App\Entity\Referentiel\TypeElement;
use App\Form\ActiviteType;
use App\Repository\ActiviteRepository;
use App\Service\_navbarExtension;
use App\Service\HistoriqueService;
use App\Service\OracleService;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/activite')]
final class ActiviteController extends AbstractController
{
    private _navbarExtension $navbarExtension;
    private OracleService $oracleService;

    public function __construct(
        _navbarExtension $navbarExtension, 
        OracleService $oracleService,
        private HistoriqueService $historiqueService
    ) {
        $this->navbarExtension = $navbarExtension;
        $this->oracleService = $oracleService;
    }

   
    #[Route('/', name: 'app_activite_index', methods: ['GET'])]
    public function index(ActiviteRepository $activiteRepository): Response
    {
        $this->oracleService->setOracleSessionParams();
        
        $activites = $activiteRepository->findAll();

        $navbarData = $this->navbarExtension->generateNavbarData(
            'Liste des activités',
            [
                ['name' => 'Accueil', 'route' => 'app_acceuil'],
                ['name' => 'Activités', 'route' => null],
            ]
        );

        return $this->render('activite/index.html.twig', [
            'navbarData' => $navbarData,
            'activites' => $activites
        ]);
    }

    
    #[Route('/new', name: 'app_activite_new', methods: ['GET','POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->oracleService->setOracleSessionParams();
        $activite = new Activite();
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $entityManager->persist($activite);
                $entityManager->flush();

                $this->historiqueService->addHistorique(
                    TypeElement::Activite,
                    $activite->getId(),
                    'Création d\'une nouvelle activité'
                );
            } catch(Exception $e) {
                // Log the exception
                error_log($e);
            }

            return $this->redirectToRoute('app_activite_index', [], Response::HTTP_SEE_OTHER);
        }

        $navbarData = $this->navbarExtension->generateNavbarData(
            'Créer une activité',
            [
                ['name' => 'Accueil', 'route' => 'app_acceuil'],
                ['name' => 'Activités', 'route' => 'app_activite_index'],
                ['name' => 'Créer', 'route' => null],
            ]
        );

        return $this->render('activite/new.html.twig', [
            'activite' => $activite,
            'form' => $form,
            'navbarData' => $navbarData,
        ]);
    }

    
    #[Route('/{id}/edit', name: 'app_activite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Activite $activite, EntityManagerInterface $entityManager): Response
    {
        $this->oracleService->setOracleSessionParams();
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $entityManager->flush();

                $this->historiqueService->addHistorique(
                    TypeElement::Activite,
                    $activite->getId(),
                    'Modification de l\'activité'
                );
            } catch(Exception $e) {
                // Log the exception
                error_log($e);
            }

            return $this->redirectToRoute('app_activite_index', [], Response::HTTP_SEE_OTHER);
        }

        $navbarData = $this->navbarExtension->generateNavbarData(
            'Modifier une activité',
            [
                ['name' => 'Accueil', 'route' => 'app_acceuil'],
                ['name' => 'Activités', 'route' => 'app_activite_index'],
                ['name' => 'Modifier', 'route' => null],
            ]
        );

        return $this->render('activite/edit.html.twig', [
            'activite' => $activite,
            'form' => $form,
            'navbarData' => $navbarData,
        ]);
    }

    
    #[Route('/{id}', name: 'app_activite_delete', methods: ['POST'])]
    public function delete(Request $request, Activite $activite, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activite->getId(), $request->request->get('_token'))) {
            try {
                $this->historiqueService->addHistorique(
                    TypeElement::Activite,
                    $activite->getId(),
                    'Suppression de l\'activité'
                );

                $entityManager->remove($activite);
                $entityManager->flush();
            } catch(Exception $e) {
                // Log the exception
                error_log($e);
            }
        }

        return $this->redirectToRoute('app_activite_index', [], Response::HTTP_SEE_OTHER);
    }

    
    #[Route('/{id}/show', name: 'app_activite_show', methods: ['GET'])]
    public function show(Activite $activite): Response
    {
        $historiques = $this->historiqueService->getHistorique(
            'Activite', 
            $activite->getId(), 
            10 // Limit to 10 entries
        );

        $navbarData = $this->navbarExtension->generateNavbarData(
            'Détails de l\'activité',
            [
                ['name' => 'Accueil', 'route' => 'app_acceuil'],
                ['name' => 'Activités', 'route' => 'app_activite_index'],
                ['name' => 'Détails', 'route' => null],
            ]
        );

        return $this->render('activite/show.html.twig', [
            'activite' => $activite,
            'navbarData' => $navbarData,
            'historiques' => $historiques,
        ]);
    }
}

templates/activite/_delete_form.html.twig
<form method="post" action="{{ path('app_activite_delete', {'id': activite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/activite/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/activite/edit.html.twig
{% extends 'inside.html.twig' %}

{% block title %}Modifier l'activité{% endblock %}

{% block main %}
    <h1>Modifier l'activité</h1>

   {{ form_start(form) }}
        <div class="row">
            <div class="col-md-6">   
                <div class="mb-3">
                    {{ form_label(form.titre, 'Titre') }}
                    {{ form_widget(form.titre, {'attr': {'class': 'form-control', 'placeholder': 'Titre de l\'activité'}}) }}
                    {{ form_errors(form.titre) }}
                </div>
                <div class="mb-3">
                    {{ form_label(form.description, 'Description') }}
                    {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder': 'Description détaillée'}}) }}
                    {{ form_errors(form.description) }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.date_debut_estimee, 'Date de début estimée') }}
                        {{ form_widget(form.date_debut_estimee, {'attr': {'class': 'form-control', 'type': 'date'}}) }}
                        {{ form_errors(form.date_debut_estimee) }}
                    </div>
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.date_fin_estimee, 'Date de fin estimée') }}
                        {{ form_widget(form.date_fin_estimee, {'attr': {'class': 'form-control', 'type': 'date'}}) }}
                        {{ form_errors(form.date_fin_estimee) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.date_debut_reel, 'Date de début réelle') }}
                        {{ form_widget(form.date_debut_reel, {'attr': {'class': 'form-control', 'type': 'date'}}) }}
                        {{ form_errors(form.date_debut_reel) }}
                    </div>
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.date_fin_reel, 'Date de fin réelle') }}
                        {{ form_widget(form.date_fin_reel, {'attr': {'class': 'form-control', 'type': 'date'}}) }}
                        {{ form_errors(form.date_fin_reel) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.projet_source, 'Projet source') }}
                        {{ form_widget(form.projet_source, {'attr': {'class': 'form-select'}, 'placeholder': 'Sélectionner un projet source'}) }}
                        {{ form_errors(form.projet_source) }}
                    </div>
                    <div class="col-md-6 mb-3">
                        {{ form_label(form.statut, 'Statut') }}
                        {{ form_widget(form.statut, {'attr': {'class': 'form-select'}, 'placeholder': 'Sélectionner un statut'}) }}
                        {{ form_errors(form.statut) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="mb-3">
            {{ form_label(form.ressources, 'Personnels associées') }}
            {{ form_widget(form.ressources, {'attr': {'class': 'form-select'}, 'placeholder': 'Sélectionner des ressources'}) }}
            {{ form_errors(form.ressources) }}
        </div>
        <div class="m-4 d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Enregistrer</button>
            <a href="{{ path('app_activite_index') }}" class="btn btn-secondary ">Retour</a>
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/activite/index.html.twig
{% extends 'inside.html.twig' %}

{% block title %}Activités 
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block main %}
<div class="container-fluid mt-4">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="mb-0">Liste des Activités</h3>
            <a href="{{ path('app_activite_new') }}" class="btn btn-primary">
                <i class="me-1 fas fa-plus"></i> Ajouter
            </a>
        </div>
        <div class="card-body">
            <table id="activiteTable" class="table table-striped table-bordered dt-responsive" style="width:100%">
                <thead>
                    <tr>
                        <th>Numéro</th>
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Date de début</th>
                        <th>Date de fin</th>
                        <th>Statut</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for activite in activites %}
                    <tr>
                        <td>{{ activite.id }}</td>
                        <td>{{ activite.titre }}</td>
                        <td>{{ activite.description|slice(0, 50)}}</td>
                        <td>
                            {% set startDate = activite.dateDebutReel ?? activite.dateDebutEstimee %}
                            {{ startDate ? startDate|date('d/m/Y') : '' }}
                        </td>
                        <td>
                            {% set endDate = activite.dateFinReel ?? activite.dateFinEstimee %}
                            {{ endDate ? endDate|date('d/m/Y') : '' }}
                        </td>
                        <td>
                            <span class="badge {% if activite.statut.nom == 'En cours' %}bg-warning{% elseif activite.statut.nom == 'Terminé' %}bg-success{% else %}bg-secondary{% endif %}">
                                {{ activite.statut.nom ?? 'Non spécifié' }}
                            </span>
                        </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a href="{{ path('app_activite_show', {'id': activite.id}) }}" class="btn btn-sm btn-info">
                                    <i class="me-1 fas fa-eye"></i>Details
                                </a>
                                <a href="{{ path('app_activite_edit', {'id': activite.id}) }}" class="btn btn-sm btn-warning">
                                    <i class="me-1 fas fa-edit"></i>Modifier
                                </a>
                                <form method="post" action="{{ path('app_activite_delete', {'id': activite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activite.id) }}">
                                    <button class="btn btn-sm btn-danger delete-activite" type="submit">
                                        <i class="me-1 fas fa-trash"></i>Supprimer
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="module">
    import $ from 'jquery';

    $(document).ready(function() {
        const table = new DataTable('#activiteTable', {
            responsive: true,
            pageLength: 10,
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "Tous"]],
            // language: {
            //     url: "//cdn.datatables.net/plug-ins/1.13.5/i18n/fr-FR.json"
            // },            
            columnDefs: [
                { targets: [0, 1, 3, 4, 5], orderable: true },
                { targets: [2, 6], orderable: false }
            ]
        });

        // Delete Activité Handler
        $('.delete-activite').on('click', function() {
            const activiteId = $(this).data('id');
            if (confirm('Êtes-vous sûr de vouloir supprimer cette activité ?')) {
                $.ajax({
                    url: "{{ path('app_activite_delete', {'id': 'PLACEHOLDER_ID'}) }}".replace('PLACEHOLDER_ID', activiteId),
                    method: 'DELETE',
                    success: function(response) {
                        location.reload();
                    },
                    error: function(xhr) {
                        alert('Une erreur s\'est produite lors de la suppression.');
                    }
                });
            }
        });
    });
    </script>
{% endblock %}

templates/activite/show.html.twig
{% extends 'inside.html.twig' %}

{% block title %}Détails complets de l'activité{% endblock %}

{% block main %}
<div class="container-fluid mt-4">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <h2 class="mb-0">
                <i class="me-1 fas fa-project-diagram" ></i>Détails de l'activité
            </h2>
            <span class="badge bg-light text-primary">ID: {{ activite.id }}</span>
        </div>
        
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <div class="card mb-4">
                        <div class="card-header ">
                            <i class="me-1 fas fa-info-circle me-2"></i>Informations Principales
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Titre</span>
                                <span>{{ activite.titre }}</span>
                            </li>
                            <li class="list-group-item">
                                <div class="fw-bold mb-2">Description</div>
                                <p class="text-muted">{{ activite.description ?: 'Aucune description' }}</p>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Statut</span>
                                <span class="badge {% if activite.statut.nom == 'Terminé' %}bg-success{% elseif activite.statut.nom == 'En cours' %}bg-warning{% else %}bg-secondary{% endif %}">
                                    {{ activite.statut.nom }}
                                </span>
                            </li>
                        </ul>
                    </div>

                    <div class="card mb-4">
                        <div class="card-header bg-warning text-white">
                            <i class="me-1 fas fa-calendar-alt me-2"></i>Dates et Délais
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Date début estimée</span>
                                <span class="badge bg-primary">
                                    {{ activite.dateDebutEstimee ? activite.formatDate(activite.dateDebutEstimee) : 'Non définie' }}
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Date fin estimée</span>
                                <span class="badge bg-primary ">
                                    {{ activite.dateFinEstimee ? activite.formatDate(activite.dateFinEstimee) : 'Non définie' }}
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Date début réelle</span>
                                <span class="badge {% if activite.dateDebutReel %}bg-success{% else %}bg-secondary{% endif %}">
                                    {{ activite.dateDebutReel ? activite.formatDate(activite.dateDebutReel) : 'Non démarrée' }}
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Date fin réelle</span>
                                <span class="badge {% if activite.dateFinReel %}bg-success{% else %}bg-secondary{% endif %}">
                                    {{ activite.dateFinReel ? activite.formatDate(activite.dateFinReel) : 'Non terminée' }}
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Durée estimée</span>
                                <span class="badge bg-primary">
                                    {{ activite.dureeEstimee ?: 'N/A' }} jours
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Durée réelle</span>
                                <span class="badge bg-primary">
                                    {{ activite.dureeReelle ?: 'N/A' }} jours
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <span class="fw-bold">Retard</span>
                                <span class="badge {% if activite.retard > 0 %}bg-danger{% else %}bg-success{% endif %}">
                                    {{ activite.retard ?: 0 }} jours
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-header bg-success text-white">
                            <i class="me-1 fas fa-users me-2"></i>Ressources
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for ressource in activite.ressources %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ ressource.Matricule }}
                                    <span class="badge bg-secondary">{{ ressource.nom }}</span>
                                </li>
                            {% else %}
                                <li class="list-group-item text-muted">Aucune ressource assignée</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="card mb-4">
                        <div class="card-header bg-danger text-white d-flex justify-content-between align-items-center">
                            <div>
                                <i class="me-1 fas fa-tasks me-2"></i>Tâches
                            </div>
                            <a href="{{ path('app_tache_new', {'activite_id': activite.id}) }}" class="btn btn-sm btn-outline-light">
                                <i class="me-1 fas fa-plus me-1"></i>Ajouter
                            </a>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for tache in activite.taches %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ tache.titre }}
                                    <span class="badge bg-primary">{{ tache.statut.nom }}</span>
                                </li>
                            {% else %}
                                <li class="list-group-item text-muted">Aucune tâche</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="card">
                        <div class="card-header bg-secondary text-white">
                            <i class="me-1 fas fa-project-diagram me-2"></i>Projet Source
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ activite.projetSource.titre }}</h5>
                            <p class="card-text text-muted">{{ activite.projetSource.description ?: 'Aucune description' }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-between">
                <a href="{{ path('app_activite_edit', {'id': activite.id}) }}" class="btn btn-warning">
                    <i class="me-1 fas fa-edit me-2"></i>Modifier
                </a>
                <a href="{{ path('app_activite_index') }}" class="btn btn-secondary">
                    <i class="me-1 fas fa-arrow-left me-2"></i>Retour
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}